### ISSUE TITLE
Add support Nextcloud 13.

### ISSUE THREAD

**Issue by sizziff** [biosonic/folderplayer#8]
You application very useful for playback music direct from file browser. Please add support Nextcloud 13.

**Comment by garzy** [comment]
This Developer are dead?

Because I need to upgrade from NextCloud v12 to v13, I'm forced to uninstall this player addon and play music with another addons that have better support.

Cheers.

**Comment by biosonic** [comment]
Sorry that you for waiting this update too long, I've been so busy lately.

App is updated to support nextCloud up to version 14.x

**Comment by ghost** [comment]
> App is updated to support nextCloud up to version 14.x

At the time of this update, Nextcloud **15** had already been released for a month. ;-)
